In [65]:
import tensorflow as tf
import numpy as np


a = np.zeros((11,11))

a[5] = np.ones((11))

a = tf.constant(a)
print(a)
f = tf.constant([[0,0,3],[0,2,0],[1,0,0]],dtype = tf.float64)
print(f)
a = tf.reshape(a,[1,11,11,1])
f =  tf.reshape(f,[3,3,1,1])

res = tf.squeeze(tf.nn.conv2d(a,f,[1,1,1,1],padding ="SAME"))
with tf.Session() as sess:
    print(sess.run(res))

Tensor("Const_80:0", shape=(11, 11), dtype=float64)
Tensor("Const_81:0", shape=(3, 3), dtype=float64)
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
